### ISSUE TITLE
[Suggestion] Make yes the default answer to watch another anime

### ISSUE THREAD

**Issue by Baitinq** [RaitaroH/adl#10]
It would be nice if when you pressed enter at the input of `Do you want to watch another anime?` it would be interpreted as yes instead of no. That way the process of watching the next episode could be much faster, as it would just be pressing enter a few times instead of having to type "y" and then enter.

Thanks

**Comment by RaitaroH** [comment]
I made it like that for the `-y` option to not get stuck in loop. Also is better to just multi select in fzf instead.

Options for this:
- keep as is
- make "Y" default for watch_another and make `-y` option choose `n`. adl exits
- as above but choose yes, watch_another always entered. User needs to CTRL+C out of adl.

**Comment by Baitinq** [comment]
Its your call man, I personally think that the default behavior should be y if you press Enter, but if it disrupts other options maybe it would be better to keep as is. Btw, what does the ` -y` option do? 

P.S.CTRL+C out of adl wouldnt be that bad imo

**Comment by RaitaroH** [comment]
adl has a `-h / --help` argument btw :)

**Comment by RaitaroH** [comment]
So I did try `-y` for the watch_another and is not going well. I made `Y` default but `-y` never engages watch another.

**Comment by RaitaroH** [comment]
@all-contributors please add @Baitinq for bugs, suggestions and code

**Comment by RaitaroH** [comment]
@all-contributors please add @Baitinq for ideas
