### ISSUE TITLE
Make mpv default player

### ISSUE THREAD

**Issue by RaitaroH** [RaitaroH/adl#13]
@Baitinq I am considering using mpv as default. I have started to use mpv a lot myself so perhaps making the change will be better. Thoughts?

**Comment by RaitaroH** [comment]
Then I will keep vlc the default considering a lot of people have that installed by default, even if mpv is recommended for anime-downloader.

**Comment by vn-ki** [comment]
I would suggest using mpv as the default player. When I remove watch, I will add the mpv keybindings from watch to `--play mpv`. This will mean that pressing `>` will allow you to go the next episode.

**Comment by RaitaroH** [comment]
@vn-ki I take you on that suggestion. Not to mention... I am using mpv myself now anyways XD.
