### ISSUE TITLE
Trackma list not being updated

### ISSUE THREAD

**Issue by Baitinq** [RaitaroH/adl#2]
After you are done watching an episode and you choose to increase the nr by 1 (next episode in trackma) when the fzf menu pops up the new nr is not there and you have to restart the program for it to be updated on the list, if not it stills shows the previous episode.

Thanks a lot (Using this all the time now)

**Comment by RaitaroH** [comment]
Yes, I know. I decided to keep it like that because fetching the list takes a while. This is why I implemented extra options.
If you consider this to be a big enough issue I will make it that the list is fetched again after the update.

**Comment by RaitaroH** [comment]
@Baitinq the latest commit af1c90c allows for multi show select. Thus updating the list was moved into watching another anime after that.
EDIT: I am also using another variable to test if list was updated and then retrieve new list. Small change but big difference.
