### ISSUE TITLE
anime dl output hidden (python 3.8 stderr)

### ISSUE THREAD

**Issue by RaitaroH** [RaitaroH/adl#21]
I noticed python changed to 3.8 on my system. After having to readd the change needed in trackma (issue https://github.com/RaitaroH/adl/issues/9) I noticed that adl had another issue: `2> /dev/null` redirection now also hides everything anime dl is outputting. This wasn't the behavior in the past. I decided to remove the null redirection here: https://github.com/RaitaroH/adl/commit/e590c2ab8ca8cef9929fe15ad7aa5cb73d929cd5 .

@Baitinq can you test this out a bit as well? Perhaps this is an anime dl bug or something in python 3.8?

**Comment by RaitaroH** [comment]
https://github.com/vn-ki/anime-downloader/issues/270

**Comment by Baitinq** [comment]
@RaitaroH sorry for the delay (Christmas holidays), I will test this when I get home.

**Comment by RaitaroH** [comment]
Damn, I wish I had your holidays.
