### ISSUE TITLE
Issue if episode number > 100

### ISSUE THREAD

**Issue by BamBalaam** [RaitaroH/adl#26]
When tracking something over 100 episodes, ADL struggles to find the next episode.

e.g. 

Selection:
```
>  |    4    Black Clover..................................................... 109 / ?
```

Post-selection
```
Black Clover > 0 / 
```

**Comment by RaitaroH** [comment]
Hmm I will take a look.

**Comment by RaitaroH** [comment]
Been busy.

**Comment by RaitaroH** [comment]
Fixed in develop branch. I will merge into master soon-ish. You can use the `adl -u` to update to develop if you want or do it manually.

**Comment by BamBalaam** [comment]
Awesome, thanks a lot @RaitaroH !

**Comment by RaitaroH** [comment]
The fix isn't pretty though, I should find a better way to do it :sweat_smile:

**Comment by BamBalaam** [comment]
To be fully honest, I would not have done better.`sed` is quite hellish, otherwise I would have submitted a PR :smile:

**Comment by RaitaroH** [comment]
@BamBalaam what do you think of this. I would like this in sed but can't get it to work there ah well ¯\\\_(ツ)\_/¯ 
```sh
process_list()    {
  perl -pe 's/\x1b\[[0-9;]*m//g ; s/^.+?[^\s]\s+(.[^\.]*)\.+\ +(\d+).[^\d]\ (\d+|\?)\s+(\d+).+$/\1|\2|\3|\4|/g'
}
```
Can you test this a bit too? In my testing things work pretty well. In terms of speed is pretty much the same as before, somehow. In terms of readability, both solutions look horrible to me. In terms of maintenance I believe this is better.
