### ISSUE TITLE
Can't use external video player with "-" in the name

### ISSUE THREAD

**Issue by HasanAbbadi** [RaitaroH/adl#32]
so, I was trying out different players to settle on one and keep watching with it.
I've tried mplayer and it worked like a charm, but the issue is that mplayer doesnt have a gui.

So i decided that I wanna use gnome-mplayer, and because the player is made out of two words that has a "-" in between
adl doesn't recognize it and it thinks that i am trying to type a command.

plz fix this soon 
thx

**Comment by RaitaroH** [comment]
The `-` gets in the way of how `adl` handles input error. So, if the user doesn't provide arguments. Unfortunately `gnome-mplayer` simply breaks that logic. What I can tell you to do, and it's simple, is to make a symlink of `gnome-mplayer` to some folder in your path.
First find where `gnome-mplayer` is:
```
where gnome-mplayer
```
Then make a shortcut of it (without `-`) in some folder in your `$PATH` like so:
```
ln -s '/usr/bin/gnome-mplayer' ~/.local/bin/gnomeplayer
```
I can modify the code elsewhere, to allow counting episodes by mplayer, but... gnome-player doesn't output something useful in my case, just some glib errors. Can you use `gnome-mplayer` in a terminal and open something, then post here.
