### ISSUE TITLE
list rewatching, paused and plan to watch

### ISSUE THREAD

**Issue by khizka** [RaitaroH/adl#38]
Is there any way I can also list these? I don't want to only see my watching list.

**Comment by RaitaroH** [comment]
Have a look at [this](https://github.com/z411/trackma/issues/576) and [this](https://github.com/z411/trackma/issues/310) which explain how you can `filter` by `paused` (for example) in trackma.
As adl is using the cli version you need something like this to not have to interact with trackma:
```bash
printf "filter paused\nls" | trackma
```

For some reason it seemed that `COLUMNS=130` wasn't working, but it does if I add a sed. 
~~2~~ 1 disadvantage with this:

- ~~I need to remove the colors from the output first~~ actually not anymore, as seen [here](https://github.com/z411/trackma/issues/79#issuecomment-480671484)
- this method might break

Anyhow here is an example:
```bash
printf "filter paused\nls" | COLUMNS=130 trackma | sed 's/\x1b\[[0-9;]*m//g' | sed -n '/^|/,${p;/results/q}' | head -n -1
```

![image](https://user-images.githubusercontent.com/19552720/142890353-47ce07d6-c82c-4be5-9e2a-17cf2643848a.png)

![image](https://user-images.githubusercontent.com/19552720/142890463-771ee817-49c4-4119-aaf6-6f44b99b7d7f.png)


@khizka if this is what you are looking for, I can try to implement it fully.

**Comment by RaitaroH** [comment]
@khizka added the feature.

**Comment by khizka** [comment]
Thank you so much! I just received the e-mail, sorry I didn't responded earlier, I had a pretty busy month. It's exactly what I needed.
