### ISSUE TITLE
adl not showing the covers in the fish shell

### ISSUE THREAD

**Issue by zenmaster3000** [RaitaroH/adl#40]
It seems that the way it execute escapes the bash shell environment of the script, so the preview will not work.
To fix this, the SHELL variable needs to be set at the beginning:

`readonly BASH_BINARY="$(which bash)"`
`     SHELL="${BASH_BINARY}" `

**Comment by RaitaroH** [comment]
Can you provide a PR for this? On my end, the covers don't work in fish, without or with your code.

This might be an upstream problem though. What is your fish/bash version?
```
fish, version 3.1.0
GNU bash, version 5.0.17(1)-release
```

**Comment by zenmaster3000** [comment]
You have to set it at the very beginning of the script.
Since I was missing some updates from the git I decided to better create an alias in fish:

`SHELL=/usr/bin/bash /home/<username>/.local/bin/adl -c`

Of course change <username> to the username in your pc.

Here are my versions:
```
fish, version 3.5.1
ueberzug 18.1.9
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

Try getting ueberzug working by itself first:
I have uploaded my test script [here](https://github.com/osalas88/ueberzug-test).
It is modified to work with fish since the original needed the fixes discussed here, so it should work for you.

**Comment by RaitaroH** [comment]
It is possible one of my shells is too old, but if it works for you that is good.
The alias fix should suffice I think. I am not sure how adding the shell would affect the script on Windows.

**Comment by zenmaster3000** [comment]
That might be but I wonder if ueberzug works on Windows.

**Comment by RaitaroH** [comment]
I am simply worried for the rest of the script having issues on Windows.
