### ISSUE TITLE
[Improvement] Sorting the fzf output by watch history.

### ISSUE THREAD

**Issue by Baitinq** [RaitaroH/adl#5]
It would be really nice if the fzf list was ordered by watch history. That way if you just finished watching an episode from series X, that series (X) would be at the top of the list, making it faster to play the next episode. Then the series you rarely watch would be at the bottom of the list and the ones you frequenlty watch at the top, saving much time.

Thanks

**Comment by RaitaroH** [comment]
Well... for that I would use something like ![frece](https://github.com/SicariusNoctis/frece). Didn't think about it but sounds nice. I will implement it.

Oh yeah btw. Check out the new `-y` option. If you use `-p mpv` then there is no input for `anime dl` either. Pretty cool. I opened a request for anime dl to have a `-y` option itself because vlc breaks with this so my function is huge and hacky. Ugh.

**Comment by RaitaroH** [comment]
So I got it to work. Unfortunately I forgot frece only works with static data so changing anime episode counters resets the database. Right now this can only be implemented using anime titles only. So it becomes like in the screenshot. I don't know this doesn't seem to add much functionality. If anything you lose the option to look at what episode the anime was at until you choose it.

I will most likely implement this as an option not as default.

![Screenshot_20190902_202354](https://user-images.githubusercontent.com/19552720/64128527-9d1ecd80-cdbf-11e9-99c1-b422c62f766e.png)

**Comment by Baitinq** [comment]
Okay, np, thanks for your work

**Comment by RaitaroH** [comment]
Again, this will be an extra option at best. So if you want it I can push the commit.

**Comment by RaitaroH** [comment]
Though again, you need to get frece for yourself.

**Comment by Baitinq** [comment]
Okay sure. Ill also try to take a look at the code to see if by any chance I could find a fix to the episodes not showing.

**Comment by RaitaroH** [comment]
They don't show up because I made the database to only show the names. I don't think frece even works with the trackma format at all. But if you can find a way to get it to work that would be nice.

EDIT: to be clear I think frece works only with lines that are the same but it can add new ones. So for ex file paths are the same and new files are added in. In our case every line will change after a trackma update so I just think it won't work at all. The only way this can work the way I made it would be to readd the data back into what `frece print ` outputs but that is getting out of hand.

**Comment by RaitaroH** [comment]
https://github.com/RaitaroH/adl/commit/34e8cf92747a8245370e683a144c1022ba9d503a

Take a look.

Also if you can find a way to get this working would be nice: https://github.com/vn-ki/anime-downloader/issues/226

**Comment by Baitinq** [comment]
Maybe you could do something like this


`IFS=$'\n'       # make newlines the only separator
set -f
for line in $(frece print $DBFILE)
do
echo "$line + [$(trackma_command)/$(trackma_command)]"    # add the episodes number to the frece output (episodes_done/number_of_episodes)
done


The output of this pipes into the fzf` ( fzf --ansi --reverse -m --prompt 'Multi-select with tab/shift-tab: ')


The trackma bit needs to say the episode number of the current line. You could search the $line in the trackma app and sed it to get the episodes done and the number of episodes. I tried to do that but I couldnt get trackma to output that. (Maybe ill try a bit more later)

**Comment by Baitinq** [comment]
Ive looked into it some more and to get the number of episodes watched and total number of episodes you could use this:

echo "$line [$(trackma search "$line" | sed -n '2p' | cut -d '/' -f1 | tail -c +6 | grep -o "[0-9]" | xargs | sed 's/ //g'
)/$(trackma search "$line" | sed -n '2p' | cut -d '/' -f2 | head -c 6 | grep -o "[0-9]" | xargs | sed 's/ //g'
)]"

Altough I am afraid it needs some workiing as it only worked with some shows (length of characters in show name or some other problem). Ill look into it tmrw.

**Comment by RaitaroH** [comment]
@Baitinq I made a few improvements. Now I can say it actually works. Information gets updated, database is properly taken care of. ~~Except for some reason `Carole & Tuesday` becomes `Carole Carole & Tuesday Tuesday` and I really can't figure it out right now.~~ Fixed that.

Also `CTRL+C` outputs crap to the screen and I need to fix that at some point.

This is the code rn:
```bash
DIR="$(dirname "$(readlink -f "$0")")"
DB_FILE="$DIR/$0.db"
ENTRIES_FILE="/tmp/$0.txt"
FZF_FILE="/tmp/$0.fzf"

select_function() { #{{{
  # Retrieve title and nr. Parse file only once
  if [[ -z "$1" ]]; then
    # entry="$(echo "$tlist" | fzf --ansi --reverse -m --prompt 'Multi-select with tab/shift-tab: ')"
    entry="$(echo "$tlist" | process_list)"
    present=""

    echo "$entry" | cut -d'|' -f1 > "$ENTRIES_FILE"
    # Create database
    if [ ! -f "$DB_FILE" ]; then
        frece init "$DB_FILE" "$ENTRIES_FILE"
    else
        frece update "$DB_FILE" "$ENTRIES_FILE" --purge-old
    fi

    cp "$DB_FILE" "$FZF_FILE"
    readarray -t lines <<< "$(frece print "$DB_FILE")"
    for line in "${lines[@]}"; do
      chosen="$(echo "$tlist" | grep "$line" | sed 's/\//\\\//g; s/|/\\|/g; s/\&/\\&/g')"
      # echo "$chosen"
      sed -i "/$line/{s/$line/$chosen/g}" "$FZF_FILE" # for every in copied database replace that line with the trackma style line
    done

    choice="$(frece print "$FZF_FILE" | fzf --ansi --reverse -m --prompt 'Multi-select with tab/shift-tab: ' | \
      (read -r x; [[ -z $x ]] || (
        chosen="$(echo "$x" | process_list)"
        echo "$chosen"
        frece increment "$DB_FILE" "$(echo $chosen | cut -d'|' -f1)" ))
      )"
  else
    entry="$1" #retrieved custom show from adl input
    present="0"
  fi

  readarray -t lines <<< "$(echo "$choice")"
  for line in "${lines[@]}"; do
    chosen=$(echo "$entry" | grep "$line")
    watch "$chosen" "$present"
    echo
  done

} #}}}
```

**Comment by Baitinq** [comment]
@RaitaroH  Nice, it works perfectly! The only problem is that the numbers before the name of each series are not updated. I would either remove them or update them after each database update.

**Comment by RaitaroH** [comment]
I will implement this frece as an optional argument. Numbers will then be out of line (tried a few awks but nah, being unaligned is worse than having some numbers out of order). You can make a PR if you want that fixes the numbers / alignment.

**Comment by RaitaroH** [comment]
The new version will be pushed soon. Closing.

**Comment by Baitinq** [comment]
Okay, will do. Thanks

**Comment by Baitinq** [comment]
@RaitaroH I think I figured out how to fix the number of the series.

`line_number=1
echo "$WHATEVER IS PIPED INTO FZF" | while IFS= read -r line ; do echo "$line" | tail -c +10 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed "s/^/${line_number}  /" | sed -e 's/^/|   /'; ((line_number++)); done`

I believe this should remove the wrong numbers and update it with new and ordered ones.

**Comment by RaitaroH** [comment]
@Baitinq Please check the most recent commit (v2.2.9 was just pushed) and open a PR with the changes you recommend.

Thank you.

**Comment by RaitaroH** [comment]
You most likely mean it to be piped into fzf before but you strip the color from it too.
So at line 86 wou would want this stuff. Still line_number >= 10 end up causing some misalignment. A second while perhaps? Not that big of deal but still. I would also personally add a few spaces before and after $line_number just so it matches the trackma output better.

```bash
      line_number=1
      choice="$(frece print "$FZF_FILE" | \
        while IFS= read -r line ; do echo "$line" | tail -c +10 | sed -e "s/^/${line_number}\ \  /; s/^/|   /"; ((line_number++)); done |\
        fzf --ansi --reverse -m --prompt 'Multi-select with tab/shift-tab: ' | \
        (read -r x; [[ -z $x ]] || (
          chosen="$(echo "$x" | process_list)"
          echo "$chosen"
          frece increment "$DB_FILE" "$(echo $chosen | cut -d'|' -f1)" ))
        )"

```

**Comment by Baitinq** [comment]
@RaitaroH I just submitted a pull request with it being implemented correclty. You can change the spacig etc how you want :)
